user = User.create!(name: 'Artur', email: 'artur.prado@youse.com.br', password: '123123')
poll = Poll.create!(name: 'Oscar', poll_date: 10.days.from_now)

poll.categories.create!(name: 'Best picture')
poll.categories.create!(name: 'Actor in a leading role')
poll.categories.create!(name: 'Actress in a leading role')
poll.categories.create!(name: 'Actor in a supporting role')
poll.categories.create!(name: 'Actress in a supporting role')
poll.categories.create!(name: 'Animated feature film')
poll.categories.create!(name: 'Cinematography')
poll.categories.create!(name: 'Costume design')
poll.categories.create!(name: 'Directing')
poll.categories.create!(name: 'Documentary (feature)')
poll.categories.create!(name: 'Documentary (short subject)')
poll.categories.create!(name: 'Film editing')
poll.categories.create!(name: 'Foreign language filme')
poll.categories.create!(name: 'Makeup and Hairstyling')
poll.categories.create!(name: 'Music (original score)')
poll.categories.create!(name: 'Music (original song)')
poll.categories.create!(name: 'Production design')
poll.categories.create!(name: 'Short filme (animated)')
poll.categories.create!(name: 'Short filme (live action)')
poll.categories.create!(name: 'Song editing')
poll.categories.create!(name: 'Song mixing')
poll.categories.create!(name: 'Visual effects')
poll.categories.create!(name: 'Writing (adapted screenplay)')
poll.categories.create!(name: 'Writing (original screenplay)')
